name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-execute:
    name: Build and execute recipe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute recipe
        env:
          GPM_IMERG_USERNAME: ${{ secrets.GPM_IMERG_USERNAME }}
          GPM_IMERG_PASSWORD: ${{ secrets.GPM_IMERG_PASSWORD }}
        run: |
          python recipes/gpm_imerg/recipe.py
